env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module

plugins:
  - react
  - react-hooks
  - '@typescript-eslint'

rules:
  indent:
    - error
    - 2

  linebreak-style:
    - error
    - unix

  quotes:
    - error
    - single

  semi:
    - error
    - never

  eqeqeq:
    - error
    - always
    - null: ignore

  space-before-blocks: error

  max-len:
    - error
    - code: 100

  '@typescript-eslint/no-explicit-any': error
  '@typescript-eslint/semi': off
